name: 'Modular CI/CD Pipeline'

on:
    push:
      branches:
        - master
        - develop
    pull_request:
      branches:
        - master
        - develop

env:
  JAVA_VERSION: '21'
  GRADLE_VERSION: '8.13'       
  JAVA_DISTRIBUTION: 'temurin'
  SPRING_PROFILES_ACTIVE: 'test'
  CACHE_KEY_SUFFIX: 'order-service-optimized'
  
permissions:
  contents: read
  checks: write
  pull-requests: write
  statuses: write

jobs:
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java Environment
        uses: cbuelvasc/actions/setup-java-base@master
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distribution: ${{ env.JAVA_DISTRIBUTION }}
          spring-profiles: ${{ env.SPRING_PROFILES_ACTIVE }}

      - name: Setup Cache Only
        id: cache
        uses: cbuelvasc/actions/cache-manager@master
        with:
          build-tool: 'gradle'
          cache-strategy: 'all'
          cache-key-suffix: ${{ env.CACHE_KEY_SUFFIX }}

      - name: Validate Build Configuration
        run: |
          if [ -f gradlew ]; then
            ./gradlew clean check --dry-run
          fi

      - name: Run Service Tests
        uses: cbuelvasc/actions/test-runner@master
        with:
          build-tool: 'gradle'
          working-directory: '.'
          test-command: './gradlew clean test integrationTest'
          coverage-enabled: true
          coverage-threshold: '85'
          fail-on-coverage-threshold: true
          publish-test-results: true    